general:
  arbitrator: &arbitrator "0xE1FDD398329C6b74C14cf19100316f0826a492d3" # Arbitration Council
  governor: &governor "0x48301Fe520f72994d32eAd72E2B6A8447873CF50" # Graph Council
  authority: &authority "0x79fd74da4c906509862c8fe93e87a9602e370bc4" # Authority that signs payment vouchers

contracts:
  Controller:
    calls:
      - fn: "setContractProxy"
        id: "0x45fc200c7e4544e457d3c5709bfe0d520442c30bbcbdaede89e8d4a4bbc19247" # keccak256('GraphToken')
        contractAddress: "${{L2GraphToken.address}}"
      - fn: "setContractProxy"
        id: "0xd362cac9cb75c10d67bcc0b7eeb0b1ef48bb5420b556c092d4fd7f758816fcf0" # keccak256('GraphTokenGateway')
        contractAddress: "${{L2GraphTokenGateway.address}}"
  L2GraphToken:
    proxy: true
    init:
      owner: *governor
      initialSupply: "0"
  L2GraphTokenGateway:
    proxy: true
    init:
      controller: "${{Controller.address}}"
